UI/WebStore/Components/BreadCrumbsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WebStore.Domain.ViewModels;
using WebStore.Interfaces.Services;

namespace WebStore.Components
{
    public class BreadCrumbsViewComponent : ViewComponent
    {
        private readonly IProductData _ProductData;

        public BreadCrumbsViewComponent(IProductData ProductData) => _ProductData = ProductData;

        public IViewComponentResult Invoke()
        {
            var model = new BreadCrumbsViewModel();

            
            if (int.TryParse(Request.Query["SectionId"], out var section_id))
            {
                model.Section = _ProductData.GetSectionById(section_id);
                if (model.Section?.ParentId is { } parent_section_id && model.Section.Parent is null)
                    model.Section.Parent = _ProductData.GetSectionById(parent_section_id)!;
            }

            if (int.TryParse(Request.Query["BrandId"], out var brand_id))
                model.Brand = _ProductData.GetBrandById(brand_id);

            if (int.TryParse(Request.RouteValues["id"]?.ToString(), out var product_id))
            {
                var SelectProduct = _ProductData.GetProductById(product_id);
                model.Product = SelectProduct?.Name;
                model.Brand = SelectProduct?.BrandId is not null ? _ProductData.GetBrandById((int)SelectProduct.BrandId) : null;
                model.Section = _ProductData.GetSectionById(SelectProduct.SectionId);
                if (model.Section?.ParentId is { } parent_section_id && model.Section.Parent is null)
                    model.Section.Parent = _ProductData.GetSectionById(parent_section_id)!;
            }
                

            return View(model);
        }
    }
}

UI/WebStore/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain;
using WebStore.Domain.ViewModels;
using WebStore.Infrastructure.Mapping;
using WebStore.Interfaces.Services;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private const string __CatalogPageSize = "CatalogPageSize";

        private readonly IProductData _ProductData;

        private readonly IConfiguration _Configuration;

        public CatalogController(IProductData ProductData, IConfiguration Configuration)
        {
            _ProductData = ProductData;
            _Configuration = Configuration;
        }
        
        public IActionResult Index(int? brandId, int? sectionId, int Page = 1, int? PageSize = null) 
        {
            var page_size = PageSize
            ?? (int.TryParse(_Configuration[__CatalogPageSize], out var value) ? value : null);

            var filter = new ProductFilter
            {
                BrandId = brandId,
                SectionId = sectionId,
                Page = Page,
                PageSize = page_size,
            };
            var (products, total_count) = _ProductData.GetProducts(filter);

            var catalog_model = new CatalogViewModel
            {
                BrandId = brandId,
                SectionId = sectionId,
                Products = products.OrderBy(p => p.Order).ToView(),
                PageViewModel = new()
                {
                    Page = Page,
                    PageSize = page_size ?? 0,
                    TotalItems = total_count,
                },
            };
            return View(catalog_model); 
        }
        public IActionResult Details(int Id)
        {
            var product = _ProductData.GetProductById(Id);
            //CultureInfo.CurrentUICulture = 
            //    CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("ru-RU");
            if (product is null)
                return NotFound();

            return View(product.ToView());
        }

        public IActionResult GetProductsView(int? BrandId, int? SectionId, int Page = 1, int? PageSize = null)
        {
            var products = GetProducts(BrandId, SectionId, Page, PageSize);
            return PartialView("Partial/_FeaturesItems", products);
        }

        private IEnumerable<ProductViewModel> GetProducts(int? BrandId, int? SectionId, int Page, int? PageSize)
        {
            var products = _ProductData.GetProducts(new()
            {
                BrandId = BrandId,
                SectionId = SectionId,
                Page = Page,
                PageSize = PageSize ?? _Configuration.GetValue(__CatalogPageSize, 6),
            });

            return products.Products.OrderBy(p => p.Order).ToView()!;
        }
    }
}

UI/WebStore/Views/Catalog/Details.cshtml
@model ProductViewModel

@{
    ViewBag.Title = "Детали товара";
}


<section>
    <div class="container">

        <vc:bread-crumbs/>

        <div class="row">
            <div class="col-sm-3">
                <partial name="Partial/_LeftSideBar"/>
            </div>

            <div class="col-sm-9 padding-right">
                <div class="product-details"><!--product-details-->
                    <div class="col-sm-5">
                        <div class="view-product">
                            <img src="~/images/shop/@Model.ImageUrl" alt="" />
                            <h3>ZOOM</h3>
                        </div>
                        <div id="similar-product" class="carousel slide" data-ride="carousel">

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    <div class="item active">
                                        <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                        <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                        <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                    </div>
                                    <div class="item">
                                        <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                        <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                        <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                    </div>
                                    <div class="item">
                                        <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                        <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                        <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                    </div>

                                </div>

                                <!-- Controls -->
                                <a class="left item-control" href="#similar-product" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                                </a>
                                <a class="right item-control" href="#similar-product" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                                </a>
                        </div>

                    </div>
                    <div class="col-sm-7">
                        <div class="product-information"><!--/product-information-->
                        @*<img src="~/images/product-details/new.jpg" class="newarrival" alt="" />*@
                            <h2>@Model.Name</h2>
                            <p>Артикул: @Model.Id.ToString("0000000")</p>
                            <img src="~/images/product-details/rating.png" alt="" />
                            <span>
                                <span>@Model.Price.ToString("C")</span>
                                <label>Количество:</label>
                                <input type="text" value="3" />
                                <a type="button" class="btn btn-default add-to-cart"
                                    asp-controller="Cart" 
                                    asp-action="Add" 
                                    asp-route-Id="@Model.Id">
                                    data-id="@Model.Id"
                                    <i class="fa fa-shopping-cart"></i>
                                    В корзину
                                </a>
                            </span>
                            <p><b>Доступность:</b> На складе</p>
                            <p><b>Состояние:</b> Новое</p>
                            <p><b>Категория:</b> @Model.Section</p>
                            <p><b>Бренд:</b> @Model.Brand</p>
                            <a href=""><img src="~/images/product-details/share.png" class="share img-responsive"  alt="" /></a>
                        </div><!--/product-information-->
                    </div>
                </div><!--/product-details-->
            </div>
        </div>
    </div>
</section>

UI/WebStore/Views/Catalog/Index.cshtml
@model CatalogViewModel

@{
    ViewBag.Title = "Каталог товаров";
}

<section id="advertisement">
	<div class="container">
		<img src="images/shop/advertisement.jpg" alt="" />
	</div>
</section>
	
<section>
	<div class="container">
		
		<vc:bread-crumbs/> 
		
		<div class="row">
			<div class="col-sm-3">
				<partial name="Partial/_LeftSideBar"/>
			</div>
				
			<div class="col-sm-9 padding-right">
				<div id="catalog-items-container">
					<partial name="Partial/_FeaturesItems" model="@Model.Products"/>
				</div>
				<paging 
					page-model="@Model.PageViewModel" 
					page-action="Index"
					page-url-SectionId="@Model.SectionId"
					page-url-BrandId="@Model.BrandId"
					page-url-PageSize="@Context.Request.Query["PageSize"]">

				</paging>
			</div>
		</div>
	</div>
</section>

@section Scripts
{
    <script src="~/lib/jquery-loading-overlay/loadingoverlay.min.js"></script>
    <script src="~/js/Catalog/CatalogLogic.js" asp-append-version="true"></script>
    
    <script>
        $(function() {
            Catalog.init({
                getViewLink: "@Url.Action("GetProductsView","Catalog")"
            });
        })
    </script>
}